# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 12:59
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('illustration', models.CharField(blank=True, max_length=200, null=True, verbose_name='illustration')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PageUnivers',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='/home/patsykakaz/RDPC/MAIN/static/media/SITES/universPNP', verbose_name='illustration')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'UNIVERS_PNP',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='SiteExtension',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('color', colorfield.fields.ColorField(default='#007099', max_length=10)),
                ('img_logo', models.ImageField(blank=True, null=True, upload_to='/home/patsykakaz/RDPC/MAIN/static/media/SITES/logo', verbose_name='logo')),
                ('img_banner', models.ImageField(blank=True, help_text="banni\xe8re pour la page d'acceuil du sous-site", null=True, upload_to='/home/patsykakaz/RDPC/MAIN/static/media/SITES/banner', verbose_name='banner')),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('title_sub', models.CharField(blank=True, max_length=128, null=True)),
                ('baseline', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'EXTENSION_SITE',
            },
            bases=('pages.page',),
        ),
    ]
