# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('illustration', models.CharField(blank=True, max_length=200, null=True, verbose_name='illustration')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'REPORTAGE',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='Reportage_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('Reportage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Reportage')),
            ],
            options={
                'verbose_name': 'GALLERIE',
            },
        ),
    ]
