# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_reportage_reportage_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportage_pic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
