# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20160404_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportage',
            name='illustration',
        ),
    ]
